# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('Title', models.CharField(max_length=128)),
                ('OriginalTitle', models.CharField(max_length=128)),
                ('Author', models.CharField(max_length=128)),
                ('entry', models.CharField(blank=True, max_length=128)),
                ('Tag', models.CharField(blank=True, max_length=128)),
                ('Publisher', models.CharField(max_length=128)),
                ('ISBN', models.BigIntegerField(null=True)),
                ('UKD', models.CharField(blank=True, max_length=128)),
                ('DatePublished', models.DateField(null=True)),
                ('BookImage', models.ImageField(blank=True, upload_to='Books')),
                ('url', models.URLField(blank=True)),
                ('slugbook', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('id', models.AutoField(default=10, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='TypeOfDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofdocument', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'TypeOfDocument',
            },
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Category'),
        ),
    ]
