# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-23 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, height_field='height_field', upload_to='pic_folder/', width_field='width_field'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
