# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import first.models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_auto_20170823_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to=first.models.upload_location)),
                ('text', models.TextField()),
                ('DatePublished', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TypeOfDocument',
        ),
    ]
